name: Unit tests
on: push

jobs:
  build:
    name: unit-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt -y install python3-dev krb5-admin-server krb5-user krb5-kdc libkrb5-dev

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest test
